project:
  title: "Introduction à R et la gestion des données"
  type: website
  
  
format: 
  html:
    toc: true
    theme: cosmo
    css: styles.css
    
    
website: 
  title: "Introduction à la gestion des données avec R"
  page-navigation: true
  search: true
  # repo-url: https://github.com/r-wasm/quarto-live
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - "index.qmd"
      - "pages/Les_bases.qmd"
      - "pages/TP1.qmd"
      - "pages/TP2.qmd"
    
# pour créer des sections :
   # contents: 
   #   - index.qmd
   #   - section: "Débuter R"
   #     - href: pages/intro.qmd
   #     contents: 
   #      - "pages/debuter-r.qmd"


# theme:
#   light: cosmo
#   dark: darkly